### ISSUE TITLE
[Feature Request]: FeedBack form

### ISSUE THREAD

**Issue by AkhilaSunesh** [ashutosh-rath02/git-re#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a feedback form 
![image](https://github.com/ashutosh-rath02/git-re/assets/140897461/c7d3aabf-208e-4ab1-b412-98d55c1847ce)
Kindly assign this issue to me

### Use Case

For all the visitors who view the website

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
How are you planning to use the data obtained?

**Comment by AkhilaSunesh** [comment]
Feedback forms also offer valuable insights into user preferences and needs, guiding design changes and content updates. 
We can understand how feasible is the website in terms of user experience.

**Comment by atharvarekhawar** [comment]
@ashutosh-rath02 instead of rating overall website we can ask it for individual pages and let them write description about their views and also provide selective options as shown in above image .

This info would be used to review current flaws and strength  in individual components and we can make changes to the website accordingly.

Even I would like to contribute to this.

**Comment by ashutosh-rath02** [comment]
@AkhilaSunesh @atharvarekhawar I want to know how you are planning to store it, when will a user be able to give  feedback and all. Give me a workflow

**Comment by atharvarekhawar** [comment]
@ashutosh-rath02 I think instead of letting user rate overall website , we can let them describe any issue they are facing in any of the part of website.

we can create a feedback form page where user can describe an issue , the form can be divided into parts like feature name and it's description and user can also upload a picture of the issue.

The form can also be used to suggest new features by the user's.

we can store this information in database and make a separate page only for the admin to showcase all the forms submitted.

we can also think of rate limiting the user to a certain number of feedback form submissions on daily basis (if necessary).

**Comment by atharvarekhawar** [comment]
@ashutosh-rath02 It can be a popup or a form on a separate page or any other method if you suggest.

**Comment by atharvarekhawar** [comment]
I don't think caching will be required as only admin can have access to it

**Comment by atharvarekhawar** [comment]
You say , how you want it and we can move ahead in that direction

**Comment by ashutosh-rath02** [comment]
If we aren't planning to display it to users it doesn't require caching. Still for now we can have stars or emojis and a feedback which will be optional. We have to make it popup or else no one's gonna go to a separate page and fill the form

**Comment by atharvarekhawar** [comment]
A popup sounds good , but when should we display it ?

I think we can keep it on every page when the page renders and the user can close it whenever he wants

**Comment by RamakrushnaBiswal** [comment]
hi @ashutosh-rath02 we can use frombricks
https://formbricks.com/

for taking feedback

**Comment by RamakrushnaBiswal** [comment]
if you want then i can work upon it

**Comment by ashutosh-rath02** [comment]
Hello @AkhilaSunesh! Your issue #208 has been closed. Thank you for your contribution!
